### ISSUE TITLE
Docs: how to label actions as protected

### ISSUE THREAD

**Issue by trentfridey** [jimjeffers/redux-jwt-protected-middleware#4]
Hi there @jimjeffers 👋  
Thanks for making this library, it is pretty well thought out.
I suggest one thing - add a section in the readme on how to label actions as protected. It took me awhile to realize that you need to do
```javascript
import { PROTECTED } from 'redux-jwt-protected-middleware'
```
and then set that on the respective actions in order for the middleware to register anything.
Thanks again

**Comment by jimjeffers** [comment]
Thanks @trentfridey I'll be sure to add it to the README. Sorry for any confusion I may have caused by not including that. Glad it is helping you!
